version: '3.7'

services:

  postgres_container:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: dnevnik
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"